apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    dadafoundry.io/create-by: liuhl
    dadafoundry.io/image-liuliu-kibana: liuliu-kibana:4.6.1
    dadafoundry.io/imageorisshow: "false"
    dadafoundry.io/imageorpublic: "false"
    dadafoundry.io/images-from: public
    openshift.io/deployment.cancelled: "2"
  creationTimestamp: null
  labels:
    app: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    app: kibana
    deploymentconfig: kibana
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kibana
        deploymentconfig: kibana
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: http://es:9200
        - name: NODE_OPTIONS
          value: --max-old-space-size=300
        image: registry.dataos.io/liuliu/kibana:4.6.1
        imagePullPolicy: Always
        name: liuliu-kibana
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-dockercfg-liuhl
      - name: deployer-dockercfg-scfec
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
status: {}
