apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/deployment.cancelled: "6"
  creationTimestamp: null
  labels:
    node: es3
  name: es-cluster3
spec:
  replicas: 1
  selector:
    node: es3
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: es
        node: es3
    spec:
      containers:
      - args:
        - -Des.cluster.name=elasticsearch-cluster
        - -Des.node.name=node-3
        - -Des.discovery.zen.ping.multicast.enabled=false
        - -Des.discovery.zen.ping_timeout=120s
        - -Des.discovery.zen.minimum_master_nodes=2
        - -Des.client.transport.ping_timeout=60s
        - -Des.discovery.zen.ping.unicast.hosts=es1,es2,es3
        image: registry.dataos.io/liuliu/elasticsearch:2.4.0 
        imagePullPolicy: IfNotPresent
        name: es-cluster3
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: elastic-storage-3
  test: false
  triggers:
  - type: ConfigChange
status: {}
