apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: es
  name: es
spec:
  ports:
  - name: port-9200
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: port-9300
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: es
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
