apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    component: kibana
    logging-infra: kibana
    provider: openshift
  name: logging-kibana
spec:
  replicas: 1
  selector:
    component: kibana
    provider: openshift
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        component: kibana
        provider: openshift
      name: kibana
    spec:
      containers:
      - env:
        - name: ES_HOST
          value: logging-es
        - name: ES_PORT
          value: "9200"
        image: registry.dataos.io/openshift/origin-logging-kibana@sha256:9847a57ef5f975f10a72775ab74745070ab5a27525f7444de3eae04e6a6afba3
        imagePullPolicy: Always
        name: kibana
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/kibana/keys
          name: kibana
          readOnly: true
      - env:
        - name: OAP_BACKEND_URL
          value: http://localhost:5601
        - name: OAP_AUTH_MODE
          value: oauth2
        - name: OAP_TRANSFORM
          value: user_header,token_header
        - name: OAP_OAUTH_ID
          value: kibana-proxy
        - name: OAP_MASTER_URL
          value: https://kubernetes.default.svc.cluster.local
        - name: OAP_PUBLIC_MASTER_URL
          value: https://dev.dataos.io:8443
        - name: OAP_LOGOUT_REDIRECT
          value: https://dev.dataos.io:8443/console/logout
        - name: OAP_MASTER_CA_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: OAP_DEBUG
          value: "false"
        image: registry.dataos.io/openshift/origin-logging-auth-proxy@sha256:440885bf0bb0088164a6a3d9cf6628daf065c2fbf641e9f96dd0163d50c62e7d
        imagePullPolicy: Always
        name: kibana-proxy
        ports:
        - containerPort: 3000
          name: oaproxy
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /secret
          name: kibana-proxy
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccount: aggregated-logging-kibana
      serviceAccountName: aggregated-logging-kibana
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kibana
        secret:
          secretName: logging-kibana
      - name: kibana-proxy
        secret:
          secretName: logging-kibana-proxy
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - kibana
      from:
        kind: ImageStreamTag
        name: logging-kibana:latest
    type: ImageChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - kibana-proxy
      from:
        kind: ImageStreamTag
        name: logging-auth-proxy:latest
    type: ImageChange
status: {}
